### ISSUE TITLE
Need to be able to change password in the User admin panel

### ISSUE THREAD

**Issue by yanicolivier** [Volontaria/API-Volontaria#136] opened 2018-02-19 16:26 UTC
## Expected behaviour
Need the missing link to change the password here : /admin/auth/user/ID_USER/change/

## Current behavior
No link

## Potential solution
[This solution is working and was tested](https://stackoverflow.com/questions/43620609/django-edit-useradmin-removes-change-password-form-from-admin-site)

```
from django.contrib.auth.admin import UserAdmin
class MyUserAdmin(UserAdmin):
    ...

admin.site.unregister(User)
admin.site.register(User, MyUserAdmin)
```

**Comment by RignonNoel** [comment] 2018-02-19 16:31
Is it a duplicate of the #130 ?

**Closed** 2018-02-19 16:36 UTC
